AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GraphQL:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs8.10
      CodeUri: apollo-lambda
      Handler: index.graphqlHandler
      Events:
        AnyRequest:
          Type: Api
          Properties:
            Path: /graphql
            Method: ANY